#!/bin/sh

set -e
PAR=ever

# check for maintainer param
if [ -n "${DEB_MAINT_PARAMS}" ]; then
	PAR=none
	if [ `echo "${DEB_MAINT_PARAMS}" | grep -v abort | grep -c remove` -eq 1 ]
	then PAR=remove; fi
fi

# check for configure|upgrade|remove|purge
case "$PAR" in

  ever|remove)
    if [ -f /usr/bin/gen-efistub-boot-entries ]; then
      # Do not abort kernel removal in case of error
      /usr/bin/gen-efistub-boot-entries >&2 || true
    fi
    ;;

esac

